### ISSUE TITLE
Flutter's communication between native code (C++) and Dart code

### ISSUE THREAD

**Issue by thaivm** [781flyingdutchman/background_downloader#101]
I'm using background_downloader for download video on some android devices, but some devices donot send notification of download status, i check logcat and saw error message like below 

`FlutterJNI: Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.bbflight.background_downloader.background. Response ID: 148`

anyone know how to fix this issue?

many thanks

**Comment by 781flyingdutchman** [comment]
If the downloader fails to send an update message to the Flutter app it should store those messages in native persistent storage (SharedPreferences on Android). If this happens you should see something like "Could not post status update -> storing locally" in your Android log.

You can get those stored messages sent to your handlers (e.g. your status update listener or your registered callback) when your app resumes (i.e. is restarted by Android) by calling `resumeFromBackground()`. See [here](https://github.com/781flyingdutchman/background_downloader#central-monitoring-and-tracking-in-a-persistent-database). Just make sure you do this _after_ you have created your listener/callback, otherwise those messages get sent into the void.

Let me know if this works
