### ISSUE TITLE
can pause/resume/delete the task ?

### ISSUE THREAD

**Issue by kennir** [781flyingdutchman/background_downloader#11]
I would like to pause a running task and then continue downloading, or delete a task completely, Can this plugin be implemented? thank you

**Comment by 781flyingdutchman** [comment]
Hi, thanks for looking at the plugin. Can you elaborate a bit on why you would want to pause and then resume a task, instead of just completing the download in the background? I can't quite imagine the situation where pausing would be an advantage. Implementing pause/resume is rather complicated and likely error-prone (for example, whether or not you can resume depends on the server, and many servers don't allow for this) so I am hesitant to do this.

**Comment by kennir** [comment]
Hi @781flyingdutchman 

Thanks for your reply.

We're working on a web-browser project，Our product has a download management page that allows the user to do all the tasks that are being downloaded (pause, continue, remove, etc.), perhaps because the product manager wants the user to have more control over the download tasks


Best regards

**Comment by 781flyingdutchman** [comment]
This will be implemented soon in V5.0

**Comment by 781flyingdutchman** [comment]
This is now available in V5.0.0.  Note that pause is dependent also on the server supporting it, so not all tasks can be paused/resumed. To see if a task is likely to be resumable, call `taskCanResume` a bit after the task has signaled it is running (because it needs server data to determine that) and if it returns false, the server does not support it.

To delete a paused task, cancel it.

Hope this is helpful.
