### ISSUE TITLE
File Upload issue

### ISSUE THREAD

**Issue by Lanpingner** [781flyingdutchman/background_downloader#121]
This might not be a bug however i am trying to upload files to a NodeJs backend server
```
FileDownloader().enqueue(UploadTask(
                                      url: "http://10.11.0.140/upload",
                                      directory: "/home/qbi1/",
                                      filename: "toDisable.txt",
                                      httpRequestMethod: "POST"));
```
                                   
This is the code i am trying to use,
How can i specify the path of the file which i want to upload

**Comment by 781flyingdutchman** [comment]
Hi, thanks for trying the package!  [This](https://pub.dev/packages/background_downloader#specifying-the-location-of-the-file-to-download-or-upload) describes how to specifiy the location of the file to upload. There are some constraints here: you cannot specify just any path, and you cannot start your directory field with a '/' because it has to be a sub-directory of the `baseDirectory`. That means you simply cannot upload directly from '/home/...' - you'll have to copy the file to a location that can be reached from one of the `BaseDirectory` enums (e.g. `BaseDirectory.temporary`, which corresponds to what you'd get if you call `getTemporaryDirectory()` using the `path_provider` package.

I appreciate this sounds a bit convoluted, but the concept is rooted in the idea of applications having their own fileSystem space, and background processes having access to only those on Android and iOS. For consistency therefore, the same rules are applied to the Desktop implementation.

Also, for an `UploadTask` you do no need to set the `httpRequestMethod` to POST, as that is the default.

Hope this helps!

**Comment by shen601020** [comment]
If it is a large file, the copying process will be painful
