### ISSUE TITLE
More control over notification text

### ISSUE THREAD

**Issue by 838** [781flyingdutchman/background_downloader#130]
It would be very nice to have more control over the notification text for specific download task.

In our app, when we download a file, we currently use a format like `harry_potter_and_the_sorcerers_stone.webpub` for the file name. However, if it were possible, we would prefer to use a more readable format, such as `Harry Potter and the Sorcerer's Stone`, as the notification title.

The readable title is also stored as `metadata` in encoded JSON along with all other metadata.

```json
{
    "bookId": 1234,
    "title": "Harry Potter and the sorcerer's stone",
    ...,
}
```

Do you have any suggestions on how we could achieve this?

**Comment by 781flyingdutchman** [comment]
Hi, you can use `configureNotificationForTask` to set a notification specifically for one task, which gives you full control over the notification text. You could also use the metaData field (and use `{metaData}`) if you don't want to set a notification for every task separately, but since you've already used that field for something else there is no other option than to use `configureNotificationForTask`. The overhead is minimal, so is there a reason why you are not using that?

**Comment by 838** [comment]
Nice, `configureNotificationForTask` was exactly what I needed. Thanks a lot.

**Comment by 781flyingdutchman** [comment]
@838 the`Task` now has a `displayName` field that can show in notification or used elsewhere (version 7.10.0)
