### ISSUE TITLE
progress information of paused task gets reset to -5.0 

### ISSUE THREAD

**Issue by Hilbert2048** [781flyingdutchman/background_downloader#136]
When a user pauses an ongoing task (e.g., when the download progress is at 50%), the progress information gets reset to -5.0. However, users expect it to display the actual progress, but the real progress information is lost.

```Dart
// Progress values representing a status
const progressComplete = 1.0;
const progressFailed = -1.0;
const progressCanceled = -2.0;
const progressNotFound = -3.0;
const progressWaitingToRetry = -4.0;
const progressPaused = -5.0;
```

**Comment by 781flyingdutchman** [comment]
Yes, negative progress values are an alternative to status updates. You should not pass progress values outside of the range 0-1 to your progress indicator. If you use tracking, the progress value in TaskRecord is not changed when the -5.0 value comes through.

**Comment by Hilbert2048** [comment]
Yes, While handling the TaskProgressUpdate, I can filter out negative progress values. However, this is not ideal. The framework shouldn't use a single progress field to convey both progress and status information.

**Comment by 781flyingdutchman** [comment]
I think that's a matter of opinion :). For example, using negative progress values to convey special state makes it possible to write only one callback function instead of two (one for state, one for progress) and some users prefer that. It is also historical, so would be a major breaking change to change it now - and it's one `if` statement for you.
