### ISSUE TITLE
Does the upload and download support resumable transfer?

### ISSUE THREAD

**Issue by kuangxinyi** [781flyingdutchman/background_downloader#138]
when app is dead and reboot ,
Does the upload and download support resumable transfer?

**Comment by 781flyingdutchman** [comment]
Hi, thanks for reaching out. If the app is killed (eg due to a crash or the user swiping the app away in the app switcher) then resume is not possible, because the killing happens instantly, leaving no time to store the resume information. If the app is closed normally then resume should be possible for downloads only (with further conditions, eg the server needs to support it etc). Uploads cannot be paused.
Does this answer your question?
