### ISSUE TITLE
[onProgress] Add count of total

### ISSUE THREAD

**Issue by iosephmagno** [781flyingdutchman/background_downloader#152]
Hello,
My compliments for this beautiful plugin.

Can we also be enabled to print `count` of `total`, instead of progress % ?

From this:
```
final result = await FileDownloader().download(task,
    onProgress: (progress) => print('Progress: ${progress * 100}%'),
);
```

To this:
```
final result = await FileDownloader().download(task,
    onProgress: (count, total) => print('Progress: downloaded $count of $total');'),
);
```

**Comment by 781flyingdutchman** [comment]
Hi, I understand what you're asking, but this is where background operations differ from regular operations (like Dio): the path to a file is not stable when using background operations: the OS may change the path every time your app is started (especially on iOS), and therefore absolute path that was valid when you create a background task may not be valid by the time the background downloader completes that task.  This is fundamentally different from how you would use Dio, and there is no way around it. That is why we use a three-part structure to determine the location of the file.

For example, on iOS, the `baseDirectory` entries in the downloader lead to directories that end like this:

946D9300-FC20-42FD-B600-3A0E92376AC3/Documents for the .applicationDocuments directory
946D9300-FC20-42FD-B600-3A0E92376AC3/Library/Caches for the .temporary directory
946D9300-FC20-42FD-B600-3A0E92376AC3/Library/Application Support for the .applicationSupport directory
946D9300-FC20-42FD-B600-3A0E92376AC3/Library for the .applicationLibrary directory
946D9300-FC20-42FD-B600-3A0E92376AC3 is the dynamic app identifier, which will change every time the app is started.

The full path that the downloader file location resolves to is the directory that baseDirectory points to, plus any directory you may have added as directory, plus the filename, where "plus" means concatenated using the path separator "/".  Note that the directory needs to be relative, i.e. it cannot start with "/" or ".".

This is also why on Android you cannot set an external path (e.g. on an SD card) as the target for the download: you have to move the file there after the download completes.

So, I understand this is a bit more cumbersome than using Dio, but it is the direct result of how Android and iOS implement background operations, and is unavoidable.

**Comment by delfme** [comment]
Thx for the explanation.

In regards to background tasks, there is also the issue on android with manufacturers blocking background. For example, workmanager tasks sometimes dont start on some android devices even with app in foreground.

https://dontkillmyapp.com

This is why we are using Dio and got peace of mind on the fact that certainty in a mobile context is only far from background operation and with app in foreground. To some extent, it is understandable: if all apps would download files when quit, battery will be drained in a snap. Yet we are still exploring the background way if we can run task always and instantly at least when app is in foreground. What’s your experience in that regards?

**Comment by 781flyingdutchman** [comment]
Hi, yes I'm aware that is an issue on some low-end Android devices.  From what I understand there are two reasons background tasks can fail, that can be addressed through configuration (if this is something you run into). There may be other reasons that I am not aware of, or can't address.

The first is forcing the use of the Documents directory instead of the Temporary directory to store the temp file for the download (which on some devices creates errors). The second is forcing the task to run as a foreground task. Both can be configured as follows:
```
FileDownloader().configure(androidConfig: [
      (Config.useCacheDir, Config.never),
      (Config.runInForeground, true)
    ]).then((result) => debugPrint('Configuration result = $result'));
```

All tasks will now use the Docs dir and run in the foreground.  Neither are great, in that you're not supposed to run every task as a foreground task, and you're supposed to use the temp dir as the OS cleans up any remnants, but if this addresses the issue then please go ahead!  Note that running a task in the foreground means you need to have a Notification set up (required by Android).
