### ISSUE TITLE
DownloadTask.withSuggestedFilename() should have a way for handling error

### ISSUE THREAD

**Issue by deadlyrazer** [781flyingdutchman/background_downloader#167]
**Describe the bug**
If `DownloadTask.withSuggestedFilename()` throws SocketException, it won't get caught because it's being caught inside of `.withSuggestedFilename()` already and not being rethrown.

**To Reproduce**
1. Set the `url` on `DownloadTask.withSuggestedFilename()` to any invalid URL.
2. await the `DownloadTask`
3. Wait a while for it to throw.
4. See SocketException being thrown and it not being caught

**Expected behavior**
The error should be allowed to be caught so we can handle the error ourselves. Or add a nullable property of `.error` which gets a value when it is caught inside the `DownloadTask` if you don't want an error to be thrown.

**Code**
```dart
  try {
  final task = await DownloadTask(
    url: 'http://192.168.0.0:0000', //Invalid URL
  ).withSuggestedFilename();

  } catch (e) {
    // Nothing happens here when SocketException is thrown
  }
```

**Additional context**
> The suggested filename is obtained by making a HEAD request to the url represented by the [DownloadTask], including urlQueryParameters and headers

Since `withSuggestedFilename()` makes an HTTP connection and normal `DownloadTask` doesn't, we only get this error on `withSuggestedFilename` and `.expectedFileSize()`, happens on Windows and Android

```dart
    try {
      final response = await DesktopDownloader.httpClient
          .head(Uri.parse(url), headers: headers);
      if ([200, 201, 202, 203, 204, 205, 206].contains(response.statusCode)) {
        return int.parse(response.headers.entries
            .firstWhere(
                (element) => element.key.toLowerCase() == 'content-length')
            .value);
      }
    } catch (e) {
     // Something should be done for us to handle the error
    }

**Comment by 781flyingdutchman** [comment]
There are many reasons why we may not be able to get a suggested filename from the server, which is why we try multiple approaches and return the original task if everything fails. That's a pretty nice error handling approach, in my opinion. If you know a server should give you a suggested filename then you can compare the filename in there original task and the one returned from WithSuggestedFilename and if they are the same you know there has been an error. I don't consider throwing the error a better solution, and even if I did changing that at this point would be a breaking change, so I'm afraid I'm going to leave this as is and suggest you use the equality test described here to test for errors.

**Comment by 781flyingdutchman** [comment]
@deadlyrazer  I created a discussion topic (#169) for how we can improve the logic around server-suggested filenames. Can you take a look and let me know what you think?
