### ISSUE TITLE
Suggestion: Provide Configurable Progress Interval

### ISSUE THREAD

**Issue by JinXiaoBing** [781flyingdutchman/background_downloader#168]
I noticed that in the ioslate.dart file at line 370, there is a method shouldSendProgressUpdate with a hard-coded threshold value of 0.02. This value is used to determine whether to send a progress update based on the difference between currentProgress and lastProgressUpdate. I would like to suggest making this threshold value a configurable parameter.

By making this threshold value configurable, it would allow users to adjust it according to their specific needs, making the code more flexible and adaptable to different use cases. This change could potentially enhance the usability of your library.

Here is the code snippet for reference:
/// Returns true if [currentProgress] > [lastProgressUpdate] + threshold and
/// [now] > [nextProgressUpdateTime]
bool shouldSendProgressUpdate(double currentProgress, DateTime now) {
  return currentProgress - lastProgressUpdate > threshold &&
      now.isAfter(nextProgressUpdateTime);
}

If you think this change is worth considering, I would be happy to create a pull request or assist with the implementation. Please let me know your thoughts on this suggestion.

**Comment by 781flyingdutchman** [comment]
Hi, thanks for reaching out with this suggestion. I don't see it as a priority feature, but I'm happy to consider a PR if you can meet the following conditions:
1) Implementation using the configuration logic already in use for various other configurations
2) Implementation for all three platforms (Android, iOS and Desktop)
3) An integration test added to the list of integration tests that tests this feature, and passes on all three platforms

I'm stating this upfront to avoid you doing a lot of work that I can't accept, and because this is not a feature I am willing to invest time in. 

Closing this issue, but - as I said - happy to consider a PR. Thanks in advance for your help!

**Comment by 781flyingdutchman** [comment]
One more thought" the update interval is dependent on two constant thresholds: the change in progress (set at 0.02 as you indicated, or 2% of the file size) and the time since last update (set at 0.5 seconds). Both need to be above that threshold, so changing 0.02 to 0.05 will not make a difference unless the file is very large (because only then is the change in progress the factor that effectively decides whether to update).

All this to say that if you implement this for the change in progress constant, then you also need to implement it for the update time interval (i.e. you need to set both). The best way would be to offer a single configuration option that sets both, eg:
`FileDownloader().configure(global: (Config.progressUpdateInterval, (0.04, const Duration(seconds: 1))` would set the update interval to 'delta progress > 0.04 AND delta time > 1 second').

I still don't quite see the value in doing all this - perhaps you can illustrate why this is important to you and others?

Finally, this is not an easy change, and because I don't prioritize it I can't really help you - sorry!
