### ISSUE TITLE
Blob Download Support?

### ISSUE THREAD

**Issue by Dracrius** [781flyingdutchman/background_downloader#250]
I'm sorry this may be a really dumb question but I don't work with html stuff a lot but does this support downloading from blobs returned as download links? I can't seem to get it to work. If it is not a supported feature already would you consider it? I'm trying to enable downloads from a local Codex Comic Book web server but it serves up download links as 'blob:...' and I'm guessing this is what is causing my downloads to fail with these results in the logs (I dashed out parts of the ip & port) 
 
```
[AndroidInAppWebViewController] (android) WebView ID 0 calling "onDownloadStartRequest" using {contentDisposition: , userAgent: Mozilla/5.0 (Linux; Android 14; sdk_gphone64_x86_64 Build/UE1A.230829.036.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.136 Mobile Safari/537.36, contentLength: 52923511, suggestedFilename: 47e9a237-0018-44b0-a006-98583be1ca3a.bin, textEncodingName: null, mimeType: application/octet-stream, url: blob:http://192.168.---.---:----/47e9a237-0018-44b0-a006-98583be1ca3a}
I/flutter (15006): blob:http://192.168.---.---:----/47e9a237-0018-44b0-a006-98583be1ca3a
I/BackgroundDownloader(15006): Enqueuing task with id `2298137483`
I/BackgroundDownloader(15006): MalformedURLException for taskId 2298137483
E/FrameTracker(15006): force finish cuj, time out: J<IME_INSETS_ANIMATION::1@1@com.mightyoakentertainment.papyrus>
```

I have confirmed I have everything else setup correctly by simply switching the download link with a known file on my network and notifications and even moving to shared storage work without issue when I trigger a download. I just can't seem to download the blob links the servers web page gives as download links.

I've kept it all pretty basic so far:

```
 onDownloadStartRequest: (controller, url) async {
          final task = await DownloadTask(
              url: url.url.toString(),
              updates: Updates.statusAndProgress, // request status and progress updates
              ).withSuggestedFilename(unique: true);
          print(task.url);
          await FileDownloader().download(task,
              onProgress: (progress) => setState(() {
                loadingPercentage = (progress * 100).round();
              }),
              onStatus: (status) {
                 if(status == TaskStatus.complete){
                   loadingPercentage = 100;
                   moveToDownloads(task);
                 } else if(status == TaskStatus.failed || status == TaskStatus.canceled){
                   loadingPercentage = 0;
                 }
          }
          );
        }
```

**Comment by 781flyingdutchman** [comment]
Hi, thanks for reaching out. Per [this](https://stackoverflow.com/a/30881444) a blob url is a browser-internal reference used to pass a regular url around. It's possible you can download the internal URL directly by simply removing the 'blob:' portion of the url, so please try that first. If that doesn't work (and it may not, because the actual http url points to a local server, not sure why) then you'll need to find a way to get a URL that can be used regularly, i.e. outside of the browser. Let me know what you find!

**Comment by 781flyingdutchman** [comment]
https://stackoverflow.com/a/16179887 suggests that the url related to the blob is indeed internal to the browser and therefore not readable outside. That would explain the localhost IP (192.168.....). If so, that means you need to figure out how to get a regular, external URL for the file you're trying to download.

**Comment by Dracrius** [comment]
> https://stackoverflow.com/a/16179887 suggests that the url related to the blob is indeed internal to the browser and therefore not readable outside. That would explain the localhost IP (192.168.....). If so, that means you need to figure out how to get a regular, external URL for the file you're trying to download.

Ya the web server is a local instance so everything is local ip's. The entire "site" requires JavaScript support so as I understand it from that post this is likely why I receive downloads as blob links. So with that said do I have to go down one of these long winded routes then?

https://github.com/guoguoguilai/flutter-webview-blob-download
https://stackoverflow.com/questions/64865972/flutter-webview-blob-pdf-download
https://github.com/pichillilorenzo/flutter_inappwebview/issues/481
https://stackoverflow.com/questions/48892390/download-blob-file-from-website-inside-android-webviewclient/48954970#48954970

My issues is I hate to implement code I don't quite understand haha and these all leave me with a head scratcher lol let alone they all seem to basically download the file without a "downloader" but maybe we can get inappwebview to just pass the internally stored data rather then the blob address? As it seems redundant as hell to take that blob path convert it to base64 make some assumption about the extension pass it to a java server only to rebuild it and finally save it. If I understand the procedure correctly.

**Comment by Dracrius** [comment]
This is the github of the server software if it helps clear anything up https://github.com/ajslater/codex

**Comment by 781flyingdutchman** [comment]
I would start by simply removing the 'blob:' prefix from the url string, by using `url: url.url.toString().subString(5)` and see if that solves the problem. If the url passed as the blob reference can be fetched from your local server, then that should work.

**Comment by Dracrius** [comment]
> I would start by simply removing the 'blob:' prefix from the url string, by using `url: url.url.toString().subString(5)` and see if that solves the problem. If the url passed as the blob reference can be fetched from your local server, then that should work.

Seemed promising but it just attempted to visit that url which caused it to autoredirect to the main page as the address isn't valid if you try and browse to it directly. This caused the download to basically just be the html but I'll attach the result.

Thanks for all your help.

**Comment by Dracrius** [comment]
[00e16b7a-8e41-4b4a-8b90-6355e8e477e5[1].txt](https://github.com/781flyingdutchman/background_downloader/files/14397036/00e16b7a-8e41-4b4a-8b90-6355e8e477e5.1.txt)
I had to give it an extension to allow me to post it!

**Comment by 781flyingdutchman** [comment]
I think you need to find a way to get the raw url of the item you want to download. Doing it through a webview isn't going to work (because that expects the item to be downloaded as a blob within that web page to render it, not to download). You should see if the Codex server has an API that allows you to query the server for a specific item, which then returns either the item directly or a URL to download it in a second step. I don't know how you got to the blob url to begin with, but you need to find a different way to get the url of the item on the server.

**Comment by Dracrius** [comment]
> I think you need to find a way to get the raw url of the item you want to download. Doing it through a webview isn't going to work (because that expects the item to be downloaded as a blob within that web page to render it, not to download). You should see if the Codex server has an API that allows you to query the server for a specific item, which then returns either the item directly or a URL to download it in a second step. I don't know how you got to the blob url to begin with, but you need to find a different way to get the url of the item on the server.

Odd ok the blob is just what the server returns when you hit any of it's download links. I'm really just trying to support the web pages download buttons. The second part of the project will be integrating an entire back end that I think may end up giving more direct links but I am trying to support the web interface first. So the blob:http.... is what is returned by inappwebviews  onDownloadStartRequest and its just a pretty standard javascript method for passing the download as the page never changes when you hit download on any platform. If anything it's inappwebview I think we'd want presenting the data differently as if I understand you correctly it should be loaded in the webview created by it while background_download is not using a webview so it can not reference it? 

While I may be the first to come across the issue I think anyone trying to download from a javascript based website may run into the same issues cause neither I or the server are doing anything particularly strange or uncommon if you know what I mean.

**Comment by Dracrius** [comment]
From here: https://stackoverflow.com/questions/14952052/convert-blob-url-to-normal-url/16179887#16179887
> A URL that was created from a JavaScript Blob can not be converted to a "normal" URL.
> 
> A blob: URL does not refer to data the exists on the server, it refers to data that your browser currently has in memory, for the current page. It will not be available on other pages, it will not be available in other browsers, and it will not be available from other computers.
> 
> Therefore it does not make sense, in general, to convert a Blob URL to a "normal" URL. If you wanted an ordinary URL, you would have to send the data from the browser to a server and have the server make it available like an ordinary file.
> 
> It is possible convert a blob: URL into a data: URL, at least in Chrome. You can use an AJAX request to "fetch" the data from the blob: URL (even though it's really just pulling it out of your browser's memory, not making an HTTP request).
> 
> Here's an example:
>```
> var blob = new Blob(["Hello, world!"], { type: 'text/plain' });
> var blobUrl = URL.createObjectURL(blob);
> 
> var xhr = new XMLHttpRequest;
> xhr.responseType = 'blob';
> 
> xhr.onload = function() {
>    var recoveredBlob = xhr.response;
> 
>    var reader = new FileReader;
> 
>    reader.onload = function() {
>      var blobAsDataUrl = reader.result;
>      window.location = blobAsDataUrl;
>    };
> 
>    reader.readAsDataURL(recoveredBlob);
> };
> 
> xhr.open('GET', blobUrl);
> xhr.send();
> ```
> 
> data: URLs are probably not what you mean by "normal" and can be problematically large. However they do work like normal URLs in that they can be shared; they're not specific to the current browser or session.

This is what I need to do haha I just don't know if I can do the same in dart. I apologize this is my first Flutter/Dart project I'm more of a C++/C# guy. It's been about a decade since I've written anything in javascript or java some I'm really rusty.

**Comment by 781flyingdutchman** [comment]
Hi, apologies, as I am also really not familiar with this blob url approach or with javascript, and since I also don't have access to the raw code I am not sure exactly what the issue is or how to resolve it. A few observations (which may not be true, but is what I think):
* When you initiate a download within a browser (or webview, but that's the same thing) you get a blob: URL which is different from a regular (data) URL in that it is a locator for a file that exists within the browser. That's why you can't simply remove the 'blob:' bit: it isn't a valid regular internet URL.
* Since presumably on the normal web page you do in fact download a file from the regular internet, somehow there needs to be a regular internet url available. Unless you can access that regular internet URL I don't think it's possible to access the file - it certainly isn't possible to do it with the background_downloader as it simply requires a regular internet URL
* The workaround you show illustrates as much: the data ("Hello world!") _already exists within the browser_ when you convert it to a raw data using `.readAsDataURL`. You could indeed try to follow the same approach and convert the blob url you have into something that reads the data - but that doesn't involve the background_donwloader. What I think is more interesting is trying to figure out how the data gets into the browser in the first place: somewhere somehow there must be a regular https call to a regular internet URL. If you can figure out what url _that_ is then you're in business, as you can use that url as the url for background_downloader
* Because of this, I suggest focusing your sleuthing on figuring out how the javascript converts your request (presumably based on a title search or something human readable) into an internet (data) url _before_ javascript downloads the data and converts that into a blob url.  As I mentioned earlier, typically this is a simple API call to the internet server (e.g. with a query in the url to trigger a search) to which the server responds with either 1) the actual file, or 2) a reference to the file in the form of an internet URL. If it's 1) then you can use that URL as the URL for the `DownloadTask` and if it's 2) then you should use the downloader to make that initial search request using `Request`, parse the result (i.e. extract the URL) and _then_ do a regular download using that url in the `DownloadTask`.

Because most of this depends on the server and the javascript code you are working with, I don't think this can be generalized. I also don't know how else I can help you with this, but let me know what you discover. Good luck!

**Comment by 781flyingdutchman** [comment]
One more comment: you say "Odd ok the blob is just what the server returns when you hit any of it's download links" and I don't think that is accurate. As you describve later on: "A blob: URL does not refer to data the exists on the server, it refers to data that your browser currently has in memory" so by the time you see a `blob:` url the data is already downloaded. Therefore, it cannot be what the server returns when you hit a download link. It has to return something else, and it likley involves client side javascript to convert it into something that then later on is referred to via the blob url. That's why I am pretty certain you have to dig deeper to understand what the actual internet url is that triggers the download. You could try using `curl` or similar packages to see what actually comes back from the server. You want to get away from webview and javascript - that really doesn't mix well with application logic.
