### ISSUE TITLE
Async getNextTask in MemoryTaskQueue

### ISSUE THREAD

**Issue by eivihnd** [781flyingdutchman/background_downloader#261]
**Problem**
Our app lets user download video files that often are more than 1GB in size, and we allow for many files to be queued for download. The url contains a token with a given lifespan. Now, if the app is closed/suspended and resumed, or a long time has passed because of previous downloads, some of those tokens might be expired resulting in a failing download.

**Possible solution**
The instructions points to subclassing MemoryTaskQueue when implementing your own queue handling.
If the getNextTask method is async, one could perform necessary work before a task is enqueued. 

We would then be able to fetch a new url from the server (using graphql to fetch signed download url) right before the download was enqueued.

**Comment by 781flyingdutchman** [comment]
For this use case I suggest copying & renaming (instead of subclassing) the `MemoryTaskQueue` and making the following changes:
1. Change the signature of getNextTask to return a Future<Task?> and implement is as you need to for your use case
2. Change line 117 to `final task = await getNextTask();`
3. Move line 121 `_readyForEnqueue = Completer();` to before line 117
4. Add a line `_readyForEnqueue.complete();` before the `return` statement currently on line 119

The reason this isn't there in its current form is that it's less elegant and arguably a little slower, although the difference is minimal. The reason you'd have to subclass is that you can't change the signature otherwise. Changing it now would potentially break things for other users who have subclassed `MemoryTaskQueue` so my preference is for you to follow the approach above instead.

Let me know if this work, and please close the issue if it does. Thanks!

**Comment by eivihnd** [comment]
Works like a charm!

I am still amazed by your dedication and pace of updates in maintaining this package!
Thank you so much!

**Comment by eivihnd** [comment]
We have started sponsoring this project. Well deserved! Hope it helps.

**Comment by 781flyingdutchman** [comment]
Thank you very much, that is motivating and encouraging!  Let me know if there's anything specific you think I should add or change to the package.
