### ISSUE TITLE
Managing rest calls (data)

### ISSUE THREAD

**Issue by sdegenaar** [781flyingdutchman/background_downloader#290]
Hi, we would love to use this package to manage downloading data for offline mode.. It would basically be a set of rest calls (9) for a product then that set done n number of times depending on how many products..could be 1000+ . Is there a way to get the results of the rest calls without having it save to a file or some in memory type operation. The only way I can see at the moment is if the results are written to a file, read the results from the file, then delete the file which seems like a big overhead for our use case.

Thanks!

**Comment by 781flyingdutchman** [comment]
I understand what you're trying to do, but the use of files to store information received when the app is suspended (in the background) is really the only way to reliably do this in a way that plays nice with the OS. The overhead is really not that big - you just read, process and delete all the files when your app wakes up.
Doing this in memory defies the purpose of a background operation, as it would require the app to wake up with every completed request.

**Comment by sdegenaar** [comment]
Thanks @781flyingdutchman . So would the workflow be better to download all the data as files first, then once complete write each files results to offline database. Or make the call, get the results from file, save to offline data, delete the file as it goes. Thanks again

**Comment by 781flyingdutchman** [comment]
I am not sure if I am understanding you completely. If you have bunch of REST calls (that you can construct as `DownloadTask` object with the appropriate headers and query arguments etc) then you can just enqueue all of them "at once" and process the results when they come in in your listener. The processing would presumably include checking the status, getting the file (with the REST call response), processing the file, deleting the file. 

If you make sure your listeners are set up at the start of your app, and you call `resumeFromBackground` after that, then all of the processed status updates will make it to your listeners (even the ones that happened  while you app was suspended) and the same listeners will process the data just as if it happened 'live'.

Note I said "at once" because if you enqueue a lot of tasks you need to give the app time to breathe. Look at `TaskQueues` in the documentation to see how you can make that easy. There may also be challenges with overloading your server and for that you can configure a `HoldingQueue` - again see the docs

**Comment by sdegenaar** [comment]
@781flyingdutchman  thanks again. Will give it a go :-)

**Comment by 781flyingdutchman** [comment]
V8.5.0 introduces the `DataTask` that is like a download/upload but without the file bit, so I think this addresses the issue you raised here.
