### ISSUE TITLE
FileDownloader().registerCallbacks downloadBatch many

### ISSUE THREAD

**Issue by sdegenaar** [781flyingdutchman/background_downloader#294]
Hi, again great package!

This is what I am trying to achieve and not sure doing the right way or missing something.

I have a product object and takes 9 rest calls to populate it and there could be heaps of products (offline mode) 

So what I have done is create a loop like :

totalOfflineProducts.forEach((product) {
        OfflineService().createProductTasks(
            productId: product.id)
});

This then creates the 9 tasks as List<DownloadTask> tasks = []; and tasks.add each one .. I have set updates: Updates.statusAndProgress when creating the task

I then var result = FileDownloader().downloadBatch(tasks....
and on the taskStatusCallback check TaskStatus.complete and then deal with the data. ie read from file, assign to appropriate object and delete the file.

then on the result.whenComplete(() async I deal with the completed object and stick it into offline database.

This is all working well except I cannot get an overall complete on the high level. I have tried 

await FileDownloader().registerCallbacks(
        taskStatusCallback: downloadStatusCallback
    );

FileDownloader().updates.listen((update) {...

FileDownloader().updates.asBroadcastStream().listen((update) {...

but none seem to fire unless there is an exception in the process and I call FileDownloader().reset();

Ideally I need this to work as explained and also if it goes into background mode it will finish everything when I call 

await FileDownloader().resumeFromBackground(); early in app on waking up.

Thanks again for any guidance!

**Comment by 781flyingdutchman** [comment]
This will not work as you intend because the batch download operation will suspend when the app suspends. The tasks will complete, but the tracking of the tasks with the batch will not work. You will have to create your own persistent storage where you keep track of the tasks and what batch they belong to . Then you will enqueue all the tasks for all the batches, and tick them off as they come in through your listener. When a task completes you check it against the other tasks in the batch to determine whether that means the entire batch completed. Because tasks may complete when your app is suspended you should definitely implement the `resumeFromBackground` functionality to make sure that your listeners capture the task updates that may have happened while the app was suspended.
A nicely integrated way to build your batch tracking is to have your storage also implement the `PersistentStorage` interface and pass it to the downloader on startup, but that's a bit more complicated.

To keep tasks linked to a batch, you can use the `metadata` field of the task and set it to a random identifier that is the same for all tasks in a batch, but unique between batches.

With respect to listening, either of the ways you describe can work. The most important thing is that you establish your listener before you start doing anything with the file downloader, including calling resume from background the best way to do this typically is to create a singleton that starts listening and keeps listening throughout the life of your application. You then interact with the Singleton objects to determine the state of your downloads, so that is also where you would hold your logic with respect to the batch completion.  The most dart like way to listen is by using the listen functionality. That is also slightly better in that it will throw an error if you somehow manage to start listening more than once, and that error tells you that you have not set it up properly.

I do not recommend using reset. It is like pressing the on off switch, not a very gentle way to cancel ongoing operations. Use `cancelTasksWithId` to cancel a large number of tasks in one go properly.

Good luck!

**Comment by sdegenaar** [comment]
Thanks very much for the reply!.

So you are saying it is better to not use the batchdownload approach and just enqueue everything and batch using the metadata tag to batch them and just deal with them as they come though in the listeners? Would then using FileDownloader().trackTasks(); and resumeFromBackground work if goes into background mode?

Much appreciated!

**Comment by 781flyingdutchman** [comment]
Yes, and yes they will work. However the built-in storage works, but is not meant to store a thousand items - you will want a better storage mechanism for that. Check out background_downloader_sql which includes an implementation of PersistentStorage using sqlite which is going to work much better for your use case. The database behind trackTasks then is an sqlite database and you can query it like sqlite. You may want to modify it a bit (e.g. store the metadata field as a separate sqlite field so you can query on it to get all tasks in a batch) by subclassing SqlitePersistentStorage
