### ISSUE TITLE
Support Longer Times

### ISSUE THREAD

**Issue by Hackmodford** [781flyingdutchman/background_downloader#3]
If you want to support longer running downloads, could you use `setForeground()` to mark it as a long running task?

https://developer.android.com/topic/libraries/architecture/workmanager/advanced/long-running

**Comment by 781flyingdutchman** [comment]
Hi, thanks for your comment! Is the limit of ~ 8 mins an issue you are experiencing? I'm asking because as I understand setting the worker task by default to the foreground (on Android) does change how the operating system handles the task, and I am not sure about the consequences of that change. I am therefore hesitant to make this change (that would affect all tasks)  unless the 8 minute timeout is a real issue.  Thanks for your input.
