### ISSUE TITLE
Option to ignore files that are already downloaded

### ISSUE THREAD

**Issue by khoadng** [781flyingdutchman/background_downloader#325]
**Is your feature request related to a problem? Please describe.**
My use case is that in my app, users have a task that runs every day to get the latest images from a remote server. Redownloading everything is a waste of time and data, as the downloaded images never change.

**Describe the solution you'd like**
An option to ignore files that are already downloaded. Ideally, there should be a way to know if a task is ignored as well.

**Describe alternatives you've considered**
I could manually check for existing files before enqueuing, but it would be more convenient if the package handled it itself.

**Comment by 781flyingdutchman** [comment]
This really sounds like something you should do outside of the package. The package is meant to be generic and compact, so any additional features should be truly valuable to a large set of use cases. As you mention, it's not hard for you to check if a file exists before deciding whether to download it, so that functionality should not move into the package.
