### ISSUE TITLE
Resume does not resume onStatus and onProgress callbacks

### ISSUE THREAD

**Issue by slaci** [781flyingdutchman/background_downloader#35]
Hello,
I have tried out your package and it seems to be very superior to the flutter_downloader, so thank you!

But when playing with pause/resume I'm struggling a bit. I cannot resume a `DownloadTask` which has `allowPause: true` and `FileDownloader().taskCanResume(task)` also says its resumable. Well, it is resumed, just the original `onStatus` and `onProgress` callbacks are not triggered anymore. Is it intended? As I see I cannot reatach callbacks when resuming.

I tried this only on android (10 on a real device, 12-13 in emulator).

Steps:
* Create a new flutter project `flutter create projname`. I'm using `3.7.12` (most recent stable).
* Replace `lib/main.dart`'s content by this gist: https://gist.github.com/slaci/ec1bae0a6648a84848f5d16e477eb540
* Bump `minSdkVersion` to 24 in `android/app/build.gradle`
* Bump `ext.kotlin_version` to `1.8.20` in `android/build.gradle` (stable flutter uses only 1.7)
* Need to find a big enought PDF file online which is accessible through https and resumable (sorry cannot provide one, working with a private one) and put the link into the code. `DownloadBtn(fileUrl: 'https://...')`.
* Press download, then pause it with the pause icon (it works). Then try to resume with the play icon. The icon will animate to pause, because `resume` returns `true`, but status and progress won't update anymore. Download will eventually complete as you can see in the logs and the file will be there.

**Comment by 781flyingdutchman** [comment]
Hi, thanks for checking out the package! The issue is in your use of the `download` method with anonymous callbacks instead of using `enqueue` with registered callbacks. A `resume` effectively re-enqueues the download task, so your call to `final result = await downloader.download` doesn't complete. Instead of using `download`, first register callbacks (that act similarly to what you use now) using `registerCallbacks` in your `initState`, then start the task with `enqueue`. That should work (it is also how the example app is done). The `download` method is really a convenience method for simple downloads that do  not get interrupted.

**Comment by 781flyingdutchman** [comment]
Hi @slaci I implemented a fix that allows you to do what you wanted to do without further modifications, and I was wondering if you could test it before I publish?  Use the following in your pubspec.yaml:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: pause_convenience
```
and see if your original code (without the modifications I suggested as an interim solution in my previous comment) works as intended (I believe it should).   Please let me know, and if so I will publish this as an update.

**Comment by slaci** [comment]
Thank you! I will try this out tomorrow. The enqueue method would be good for me also, just tried to use it as easy as possible.

**Comment by slaci** [comment]
I have tried it and I can resume the download now, but only once. The second time I try to pause, I get into `TaskStatus.failed` status immediately.

In [TaskWorker.kt#557](https://github.com/781flyingdutchman/background_downloader/blob/pause_convenience/android/src/main/kotlin/com/bbflight/background_downloader/TaskWorker.kt#L557) the `taskCanResume` is false, so I get `Task 3325076481 cannot resume, therefore pause failed` message in the console. As I see its a kindof global variable, which is updated only at some points, but not before resume. Do you remember why isn't this info saved to the task the first time it is determined? I think it cannot really change, because its not likely the server sends `Accept-ranges` for the first time, then it does not send it anymore, or suddenly the the request is changed to post. What do you think?

**Comment by slaci** [comment]
I've just rewritten the whole thing to use `Bloc` and `enqueue`, but sadly that has the same issue. When pausing the download for the second time, I get the failure, so its not specific to the conveinence `download` method.

**Comment by 781flyingdutchman** [comment]
Thanks for testing. Sounds like the original problem is fixed, but the server response to a resume in your case is different from what the plugin expects, because it isn't setting the accept-ranges header when requesting a partial download (i.e. a resume). That is different from normal behavior (see the example app where multiple pause/resume works fine), but you're right that it is unlikely that the server wouldn't accept ranges on resume, even if it doesn't repeat that.

I've made a small change to the branch that does two thing:
1. log the 'Accept-Ranges' header
2. assumes resume is possible when already resuming

Can you run this and see if it fixes the problem? Can you also let me know what exactly the accept-ranges header is initially, and upon resume?  It's possible the accept-ranges header is more complex than I expect and we can still use it. I'm also concerned that adopting this non-standard behavior on iOS is more complicated, so would appreciate understanding the server response more clearly.

Thanks!

**Comment by slaci** [comment]
Okay I debugged it a bit, these are my findings:

Headers got from my server on resume:
```
I/TaskWorker(10547): Header null => [HTTP/1.1 206 Partial Content]
I/TaskWorker(10547): Header Connection => [Keep-Alive]
I/TaskWorker(10547): Header Content-Length => [50680640]
I/TaskWorker(10547): Header Content-Range => [bytes 3146790-53827429/53827430]
I/TaskWorker(10547): Header Content-Type => [application/pdf]
I/TaskWorker(10547): Header Date => [Tue, 25 Apr 2023 07:42:15 GMT]
I/TaskWorker(10547): Header ETag => ["60b73428-3355766"]
I/TaskWorker(10547): Header Keep-Alive => [timeout=5, max=100]
I/TaskWorker(10547): Header Last-Modified => [Wed, 02 Jun 2021 07:32:56 GMT]
I/TaskWorker(10547): Header Server => [nginx/1.23.4]
I/TaskWorker(10547): Header Via => [1.1 slaci.dev.deducted]
I/TaskWorker(10547): Header X-Android-Received-Millis => [1682408534253]
I/TaskWorker(10547): Header X-Android-Response-Source => [NETWORK 206]
I/TaskWorker(10547): Header X-Android-Selected-Protocol => [http/1.1]
I/TaskWorker(10547): Header X-Android-Sent-Millis => [1682408534194]
```

On resume you send the Ranges header (`I/TaskWorker(10547): ContentRanges: [bytes 3146790-53827429/53827430]` ) and when that exists, then nginx (I'm using stock `nginx:alpine` container, though its behind an apache proxy) does not send `Accept-Ranges`, instead it sends a `Content-Range` header (at least that's what I see).

You added `isResumeParam` to the condition, which makes it work, but maybe its better to check for the `Content-Range` header instead.

On the initial request I get these headers fyi:

```
I/TaskWorker(10547): Header null => [HTTP/1.1 200 OK]
I/TaskWorker(10547): Header Accept-Ranges => [bytes]
I/TaskWorker(10547): Header Connection => [Keep-Alive]
I/TaskWorker(10547): Header Content-Length => [53827430]
I/TaskWorker(10547): Header Content-Type => [application/pdf]
I/TaskWorker(10547): Header Date => [Tue, 25 Apr 2023 07:42:07 GMT]
I/TaskWorker(10547): Header ETag => ["60b73428-3355766"]
I/TaskWorker(10547): Header Keep-Alive => [timeout=5, max=100]
I/TaskWorker(10547): Header Last-Modified => [Wed, 02 Jun 2021 07:32:56 GMT]
I/TaskWorker(10547): Header Server => [nginx/1.23.4]
I/TaskWorker(10547): Header Via => [1.1 slaci.dev.deducted]
I/TaskWorker(10547): Header X-Android-Received-Millis => [1682408526323]
I/TaskWorker(10547): Header X-Android-Response-Source => [NETWORK 200]
I/TaskWorker(10547): Header X-Android-Selected-Protocol => [http/1.1]
I/TaskWorker(10547): Header X-Android-Sent-Millis => [1682408526268]
```

**Comment by 781flyingdutchman** [comment]
Thanks for your help! Interesting how a very common server is not fully compliant with the spec! I've gone with the solution where if it's a 206 response I assume the task can be paused/resumed. Seems reasonable.  I'll publish this together with a few other fixes
