### ISSUE TITLE
Use the file name from content disposition response headers

### ISSUE THREAD

**Issue by rekire** [781flyingdutchman/background_downloader#37]
When I was trying the library I noticed that the notification is showing a strange file name which is derived from the download URL.

Therefore I would ask you to respect (as far as possible, I would guess impossible on iOS) to take the filename dynamically (when given) from the [`Content-Disposition`](https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Disposition) response header.

**Comment by 781flyingdutchman** [comment]
Thanks for the suggestion @rekire - I have implemented it by introducing a method `withSuggestedFilename` that can be called on a `DownloadTask`. That way, we preserve the notion that the Task already contains the filename _before_ starting the download, so you can continue to use it on the Dart side. You can use it as follows:
```
   final task = await DownloadTask(url: 'https://google.com')
       .withSuggestedFilename(unique: true);
```
Then enqueue the task or use `download`. The way it works is it does a HEAD request to get the headers that contain Content-Disposition, uses that to derive the filename (including UTF-8 encoded filename) or URL last path segment (if not available in disposition), then modifies it further if necessary to create a filename that does not already exist.

Implemented in V5.5.0 along with a few bug fixes

**Comment by markst** [comment]
awesome; thanks for this!

**Comment by 781flyingdutchman** [comment]
Reopening because you are right, we should follow redirects. I also opened issue #93 as the `request` implementation doesn't follow redirects either, and should.

**Comment by 781flyingdutchman** [comment]
Hi, I actually believe we _do_ follow redirects, as the Dart implementation in the http package does. However, I am not getting a suggested filename from your server. I use this code to test (in integration_test):
```
    testWidgets('get request with redirect', (widgetTester) async {
      final request = Request(url: 'https://airnet.org.au/omnystudio/3pbs/deeep-space/202305150900/aac_mid.m4a', httpRequestMethod: 'HEAD');
      final response = await FileDownloader().request(request);
      print('code = ${response.statusCode} with headers ${response.headers}');
      expect(response.statusCode, equals(200));
      expect(response.body.startsWith("{'args': {'redirected': 'true'}"), isTrue); // from original test
    });
```
This is similar to `withSuggestedFilename` in that it uses the `httpClient().head` method to probe the server. I get a 200 result code (so it followed the redirects) but the head is:
`{x-stw-site: AUS, connection: keep-alive, cache-control: private, max-age=146051376512, last-modified: Mon, 17 Jul 2023 15:23:12 GMT, date: Mon, 17 Jul 2023 15:23:12 GMT, access-control-allow-origin: *, x-stw-mc: SYD2-INTERGRID-MC01_S001, content-type: audio/mpeg, access-control-allow-headers: *, accept-ranges: bytes, access-control-allow-methods: GET, HEAD, content-length: 117967376, expires: Tue, 23 Sep 6651 02:11:44 GMT}` which does not contain a `content-disposition` header that is needed to extract the suggested filename from. If that is missing, the method falls back to using the url.

So, I believe this issue is with your server's response, not the code. Let me know if you think differently.

By the way, if you change your url with `getRedirectTestUrl` and remove the `HEAD` `httpMethod`, the test passes.

**Comment by markst** [comment]
Thanks for looking into this @781flyingdutchman.

I'll do some more digging. Does seem `content-disposition` is missing, however previous use of `flutter_downloader` with this url would use the correct filename.

When downloading that link on Safari the filename resolves to the correct filename.

**Comment by 781flyingdutchman** [comment]
One possibility is that the content-disposition header is included with the actual GET request, but not on HEAD. I have to use HEAD because the architecture of the downloader is that the filename is known before starting the download, so i can't truly derive it from the content-disposition upon download. Is there another way to get the header without downloading the whole file?

**Comment by markst** [comment]
ah not to stress too much. I just thought it would be simple to use the  [suggestedfilename](https://developer.apple.com/documentation/foundation/urlresponse/1415924-suggestedfilename) during the move file upon `didFinishDownloadingTo`.

**Comment by 781flyingdutchman** [comment]
I've looked into it a bit further and really don't feel comfortable implementing this:
* It's fairly complicated to flow the 'amended' task (with the server-supplied filename) from the native platform back, via the status and progress updates, to the developer side of the code
* I'm concerned that having two versions of the task floating around (one with {filename} or something like that, and another with the actual filename) is going to lead to confusion and lots of filed bugs. 

I'm going to close this again for now, but may reconsider if there are indications that `withSuggestedFilename` is not working for folks - sorry!
