### ISSUE TITLE
taskFinished returns true even if there are running tasks

### ISSUE THREAD

**Issue by philitell** [781flyingdutchman/background_downloader#419]
**Describe the bug**
I'm using a listener to check TaskStatusUpdates. Within the listener-method (onTaskStatusUpdate) i am checking if there are any active tasks left in order to update a provider to inform the user that the last download finished.
For this purpose i'm calling the method tasksFinished() (for the group that the task belongs to) inside the listener-method.
It seem there are cases where the result of this method is true but the status of the current task is running or enqueued. The logs (added below) show that there are situations where onTaskStatusUpdate is called for a task with an active state but the result of the tasksFinished()-call inside this method is true. This occurs especially when not configuring a holdingQueue. This result in very fast downloads but seems to create some sort of race-condition that might cause this issue.

**To Reproduce**
- 

**Expected behavior**
-

**Logs**
Here are logs of my implementation that monitor this special cases
```
I/flutter (11730): -----------------------------------------------------------------
I/flutter (11730): | INFO: 2024-11-26 14:46:48.890320 - ManagerLogger: Handling taskStatusUpdate for group: acc4c055-fb8c-4f54-bafd-af1c8735d30d with status: TaskStatus.running
I/flutter (11730): -----------------------------------------------------------------
V/BackgroundDownloader(11730): Returning 0 unfinished tasks in group acc4c055-fb8c-4f54-bafd-af1c8735d30d
I/flutter (11730): -----------------------------------------------------------------
I/flutter (11730): | INFO: 2024-11-26 14:46:48.927989 - ManagerLogger: All tasks of group acc4c055-fb8c-4f54-bafd-af1c8735d30d are finished
I/flutter (11730): -----------------------------------------------------------------
I/flutter (11730): -----------------------------------------------------------------
I/flutter (11730): | SEVERE: 2024-11-26 14:46:48.928583 - ManagerLogger: Found situation where taskFinished is true and state of task update is TaskStatus.running
I/flutter (11730): -----------------------------------------------------------------
I/flutter (11730): -----------------------------------------------------------------
I/flutter (11730): | INFO: 2024-11-26 14:46:48.932114 - RepositoryLogger: Result of task completion check: 10 of 10 tasks are completed
I/flutter (11730): -----------------------------------------------------------------
```

*Code**
This is my basic configuration
```
     await FileDownloader().ready;
      final configResult = await FileDownloader().configure(
        globalConfig: [
          (Config.requestTimeout, const Duration(seconds: 100)),
          (Config.checkAvailableSpace, 500),
          (Config.holdingQueue, null),
        ],
        androidConfig: [
          (Config.useCacheDir, Config.whenAble),
        ],
        iOSConfig: [
          (Config.localize, {"Cancel": S.current.stopIt}),
        ],
      );

      // Register an event listener to process status and progress updates
      _ref.read(fileTransferTaskStatusUpdateProvider);

      repositoryLogger.info("Start persistent task tracking");
      await FileDownloader().trackTasks();

      repositoryLogger.info("Check for events that happened while the app was in the background");
      await FileDownloader().resumeFromBackground();
```

This is the onTaskStatusUpdate method:
```
 Future<void> handleTaskStatusUpdate({required TaskStatusUpdate taskStatusUpdate}) async {
    final String bciObjectId = taskStatusUpdate.task.group;
   
........

    FileTransferManagerStatus? newManagerStatus;
    try {
      if (await FileDownloader().tasksFinished(group: bciObjectId)) {
        managerLogger.info("All tasks of group $bciObjectId are finished");
        if ([TaskStatus.running, TaskStatus.enqueued].contains(taskStatusUpdate.status)) {
          managerLogger.severe(
              "Found situation where taskFinished 
```

**Comment by 781flyingdutchman** [comment]
I wonder if you run into the issue described in the documentation:
NOTE: Only tasks that are active (ie. not in a final state) are guaranteed to be returned or counted, but returning a task does not guarantee that it is active. This means that if you check tasksFinished when processing a task update, the task you received an update for may still show as 'active', even though it just finished, and result in false being returned. To fix this, pass that task's taskId as ignoreTaskId to the tasksFinished call, and it will be ignored for the purpose of testing if all tasks are finished:
```
void downloadStatusCallback(TaskStatusUpdate update) async {
    // process your status update, then check if all tasks are finished
    final bool allTasksFinished = update.status.isFinalState && 
        await FileDownloader().tasksFinished(ignoreTaskId: update.task.taskId) ;
    print('All tasks finished: $allTasksFinished');
  }
```

This issue is caused by the unpredictability of when the listener is called in Dart (since it's async and runs on the Dart event loop) and when the status is updated in the Android system (which may run on a different thread), causing a race condition, and the issue is present for all task queries (like `allTasks`). The use of `ignoreTaskId` in `tasksFinished` works if you are processing an update for a specific task (because you just received the update, you already know whether or not that task is finished so you can ignore it).  For other situations you have to allow for some time for the states of the tasks in Android to align to state you detected using the status update, or choose to use just one way to determine the state of all tasks.

**Comment by philitell** [comment]
I have done further testing and can confirm that is possible to:
 - rely completely on the db-entries and monitor "allTasksFinished" with db-listeners - which is possible with isar-db OR
 - to wait until all events are proccessed correctly (which leads to a "virtual" progress - which takes a little longer to complete than the real progress) and determine "allTaskFinished" based on e.g. number of finished Tasks counted in the taskUpdate-listener-method vs number of enqueued tasks.

Both approaches don't check for an empty queue but keep track of the task enqueued and the tasks that have finished.
 
All in all it seems not to be a good idea to determine "allTasksFinished" inside the taskUpdate-listener method.

**Comment by 781flyingdutchman** [comment]
Yes, the Dart message queue runs at its own pace, so the state you derive from updates is not always consistent with the state you get from the database, but they will eventually be consistent.

Android sets limits on how frequently notifications can be updated, so download notifications are queued and processed not faster than 5 per second. If your downloads go fast, you may be waiting as much as n/5 seconds for the notifications to catch up. If that's an issue, then you may be better off just setting a static notification when you start your downloads, and remove it when all are done. I believe that happens when you don't use numFinished and numTotal in the notification (so it doesn't change for the duration of the group).

Also note that on iOS there is no option to change a notification, which means that for group notifications that have numFinished in them you get a new notification every time that state changes, which is annoying for the user, so I suggest  similarly using a static notification for the running state on iOS.

**Comment by philitell** [comment]
@781flyingdutchman Thank you very much for all the explanations!!! This is really a great package!

**Comment by 781flyingdutchman** [comment]
Also, not sure why you are setting a max concurrent but you should try without: modern HTTP/2 servers actually do quite well with multiple simultaneous downloads, and Android does a decent job managing how many tasks it let's run in parallel anyway, so you may find that you get better download times without compromising the main app when doing it this way.

You should also set your task such that it does not generate progress updates (only status), for short tasks.

**Comment by 781flyingdutchman** [comment]
> Both approaches don't check for an empty queue but keep track of the task enqueued and the tasks that have finished

Yes, that sounds like more solid logic than relying on the queue not getting to empty, and also better to take one source of truth for your overall state (in your case the database).

> All in all it seems not to be a good idea to use allTasksFinished() inside the taskUpdate-listener method

Yes, it's a relatively expensive operation (it queries the WorkManager database every time you call it) so probably not best suited for many shorter tasks.
