### ISSUE TITLE
Whether timeoutIntervalForResource parameters can be exposed to developers, used for custom timeout？

### ISSUE THREAD

**Issue by coder-dongjiayi** [781flyingdutchman/background_downloader#44]
I am downloading a 10M file, but the file server may be far away from the user. For example, the file server is in China, but the user may be in England. Users are waiting for the file download is complete, if timeoutIntervalForResource is very large, the user may have been waiting for the download page. At this time, we may set the timeout time to 60 seconds. After 60 seconds, if the file server does not respond, it indicates that the request time out is requested. We need to inform the user that the network is abnormal and need to re-download. I think timeoutIntervalForResource this parameter should be exposed to developers, by a business to determine how much the value should be

**Comment by 781flyingdutchman** [comment]
Hi, thanks for moving the discussion to this separate issue!  I think I understand what you are trying to accomplish. Unfortunately I don't think the `timeoutIntervalForResource` is the right approach for this: 

1. It is unique to iOS (there is no conceptual equivalent in Android or on desktop) 
2. The value can only be set by UrlSession, which means that all tasks would have the same constraint
3. It goes against the spirit of a background download, where the whole idea is that you can 'set and forget' the download without worrying about its immediate completion. This is why the default for `timeoutIntervalForResource` on iOS is 7 days!

As I said, I do understand your use case, which is if a download is actually time sensitive. Because that is not the typical use case for the background_downloader, I wonder if we can add this behavior to the `download` method only, which is the one that does suggest an immediate download and response. 

The `download` method currently has optional callbacks `onStatus` and `onProgress`, and we could add a callback `onTimer` along with a `Duration` value in, say, `timeInterval` with a default value of say 1 minute. The idea would be that if an `onTimer` callback is given, we start a repeating timer and call the callback when the timer fires, passing an integer value `count` indicating how many times the timer has fired. It is then up to the developer to define what happens when the callback is called: they could for example cancel the task, or they could show a warning in the UI that the download is slow. For a more sophisticated approach you could set `timeInterval` to 10 seconds, and when `count` is 3 (i.e. 30 seconds have passed) you show a warning, and on `count` == 6 (a minute has passed) you cancel the download (which also cancels the timer). 

Limiting this to the `download` method arguments only has several advantages:
1. It does not become something every `Task` needs to be able to do
2. It keeps it limited to those occasions when you already expect the download to complete while the app is running, and not in occasions where you don't (the `enqueue` method in particular is the 'fire and forget' approach to downloads, and the assumption there is that there could be a long wait before a download completes, e.g. because there are multiple big files in front of the queue, or you allow waiting for WiFi).
3. It is consistent across platforms, because the entire logic is implemented in Dart (not in the native code where it is much harder to achieve consistency across platforms).

Let me know what you think!

**Comment by coder-dongjiayi** [comment]
ok, I am understand. I see what you mean。
Maybe using timer/Duration in the dart  is a better option for multiple platforms.
Thank you very much.

**Comment by 781flyingdutchman** [comment]
Implemented in V6.0.0:

The `download`, `upload`, `downloadBatch` and `uploadBatch` methods now take an optional `onElapsedTime` callback that is called at regular intervals (defined by the optional `elapsedTimeInterval` which defaults to 5 seconds) with the time elapsed since the call was made. This can be used to trigger UI warnings (e.g. 'this is taking rather long') or to cancel the task if it does not complete within a desired time. For performance reasons the `elapsedTimeInterval` should not be set to a value less than one second, and this mechanism should not be used to indicate progress.
