### ISSUE TITLE
Specify direct path for upload, instead of using BaseDirectory

### ISSUE THREAD

**Issue by AppInstaller1** [781flyingdutchman/background_downloader#57]
Currently, files have to be copied to a local directory (BaseDirectory) for uploading, which seems very inefficient for uploading large files. Being able to specify a direct path for uploading seems essential, especially for desktop apps. It would be nice to be able to specify the path directly in the directory parameter by setting BaseDirectory to none. (or any better way than this, if possible)

The current way works well for downloads, but seems very inefficient for uploads.

**Comment by 781flyingdutchman** [comment]
As indicated in the readme, for compatibility with mobile platforms we cannot support absolute paths.

**Comment by onism0106** [comment]
why not support the download directory? It's can be accessed on all platforms

**Comment by 781flyingdutchman** [comment]
Hi, the download directory is supported, with an extra step. You need to download the file first (e.g. to the temporary directory) and then move it to shared storage. For example:
```
  final task = DownloadTask(url: 'https://www.google.com',
    filename: 'test.html',
    baseDirectory: BaseDirectory.temporary)
  final result = await FileDownloader().download(task);
  if (result.status == TaskStatus.complete) {
    final filePath =  await FileDownloader()
        .moveToSharedStorage(task, SharedStorage.downloads);
    // filePath is now the path to the file, or null if unsuccessful
  }
```

The reason for this two-step approach is that Downloads is not typically private to the app. The `download` and `enqueue` methods are designed to only download to the private app space. Moving a file to a shared storage location may require additional permissions, and is therefore handled as a separate step, so that we can keep the normal download functionality simple.
