### ISSUE TITLE
Canceled tasks receive a status update with status `TaskStatus.complete`

### ISSUE THREAD

**Issue by mklepaczko** [781flyingdutchman/background_downloader#67]
When canceling download tasks and using the callback and `_downloader.trackTasks();`, canceled tasks first reveive a status of `TaskStatus.canceled` and after a status update as `TaskStatus.complete`.

Here is an example of debug print for 8 tasks and canceling after the 5th:

```
flutter: Number of tasks is 8 enqueued
flutter: Download task for taskId 2994652373 finished
flutter: Download task for taskId 4149728288 finished
flutter: Download task for taskId 960639505 finished
flutter: Download task for taskId 4149728288 finished
flutter: Download task for taskId 1628778387 finished
flutter: Canceled taskId 3790078376
flutter: Canceled taskId 960639505
flutter: Canceled taskId 2204538363
flutter: Canceled taskId 4135404628
flutter: Canceled taskId 2573871163
flutter: Download task for taskId 3790078376 finished,
flutter: Download task for taskId 2204538363 finished
flutter: Download task for taskId 960639505 finished
flutter: Download task for taskId 4135404628 finished
flutter: Some download tasks failed for audiobookId 57188
```

Shoudln't these tasks just have a last update as `canceled` ?

```dart
  Future myDownloadStatusCallback(TaskStatusUpdate update) async {
    switch (update.status) {
      case TaskStatus.enqueued:
        break;
      case TaskStatus.notFound:
        break;
      case TaskStatus.failed:
        break;
      case TaskStatus.canceled:
        debugPrint('Canceled taskId ${update.task.taskId}');
        break;
      case TaskStatus.waitingToRetry:
        break;
      case TaskStatus.running:
        break;
      break;
      case TaskStatus.complete:
        debugPrint(
            'Download task for taskId ${update.task.taskId} finished');

        break;
      case TaskStatus.paused:
        break;
    }
  }
```

**Comment by mklepaczko** [comment]
And yes I only set the trackTasks once in an initializer.

**Comment by 781flyingdutchman** [comment]
Can you check if it has the same issue when running on an Android device or simulator?

**Comment by 781flyingdutchman** [comment]
Hi!  I've tried to replicate this in a test with the following code, running on an iPhone 14 Pro:
```dart
    testWidgets('no trailing status updates after cancel',
        (widgetTester) async {
      FileDownloader().registerCallbacks(
          taskStatusCallback: statusCallback,
          taskProgressCallback: progressCallback);
      await FileDownloader().trackTasks();
      Task? task5;
      for (var i = 1; i < 8; i++) {
        task = DownloadTask(url: urlWithContentLength, updates: Updates.status);
        expect(await FileDownloader().enqueue(task), isTrue);
        if (i == 5) {
          task5 = task;
        }
      }
      await Future.delayed(const Duration(seconds: 3));
      expect(await FileDownloader().cancelTaskWithId(task5!.taskId), isTrue);
      await Future.delayed(const Duration(seconds: 100));
    });
```

Unfortunately I cannot replicate the issue: the callbacks print the incoming status and progress updates and it all works as expected. I wonder if the issue is with `trackTasks`, so I just want to check two things:
1. It needs to be `await FileDownloader().trackTasks()` -> without `await` the code may execute in parallel with, or even after the downloads have started or completed. This matters because of the next thing
2. The `trackTasks` call defaults to marking a task as `.complete` if the file referenced by the `Task` exists. So, if for whatever reason the file referenced by Task5 already exists (e.g. it was downloaded before and is still there, or you use the same filename for multiple tasks) then this will mark Task5 as complete and emit a `.complete` status.  If you don't want to mark existing files as `.complete` then set argument `markDownloadedComplete` to `false` when calling `trackTasks`.

Does any of this hint at what the issue might be? If not, I suggest testing with the following:
1. Make sure all files referenced by the tasks you enqueue are deleted before starting the enqueue, and make sure the filename for each task is unique, then see if the issue is gone
2. Omit the `trackTasks` call, and see if the issue is gone
3. Add `markDownloadedComplete = false` to the `trackTasks` call and see if the issue is gone

Sorry this isn't more helpful - let me know what you find out

**Comment by mklepaczko** [comment]
Sorry, I m away all week, I will get back to you beginning next week.

W dniu wt., 13.06.2023 o 17:23 Shahmirzali ***@***.***>
napisał(a):

**Comment by mklepaczko** [comment]
Hello,

Sorry for this late reply, I just got back to it and found my sin :) for some reason I though that I needed to enqueue all tasks from a list first and then call `downloadBatch`, thus resulting in duplicate callbacks. Either it worked like that in Flutter_downloader or I just made that up myself.

Sorry for taking your time, I close this one. Thanks for your support!
Mkl
