### ISSUE TITLE
Set the TaskException of TaskStatusUpdate when status is TaskStatus.notFound

### ISSUE THREAD

**Issue by cal-g** [781flyingdutchman/background_downloader#80]
Hi @781flyingdutchman , currently when the request results in a 404 Not Found error the `TaskStatusUpdate.exception` is null. Can the `exception` be set as a `TaskHttpException` ?
Thanks

**Comment by 781flyingdutchman** [comment]
Hi @cal-g , the way it's set up is that an Exception is only provided when the status is `.failed` and changing that has pretty significant implications. The notFound status is intentionally a special status that differs from failed, so that for example no retries will be attempted. Unfortunately this is therefore not a change I can make.

**Comment by 781flyingdutchman** [comment]
Just to add another thought: if what you're looking for is more info on the nature of the NotFound result, I suggest using the `request` method (which accepts the same `Task` you used for the failed download) and inspecting the body of the returned response. Yes it's an extra step, but in the vast majority of cases, knowing a url was not found is in itself enough information to act upon.

**Comment by 781flyingdutchman** [comment]
Hi @cal-g I think this is now implemented as a byproduct of issue #100 : `TaskStatusUpdate.responseBody` contains the server response for a 404 error (and the `status` remains `.notFound`, `taskException` remains null). Please check it out!
