### ISSUE TITLE
Download always failed in after being built and installed on real device

### ISSUE THREAD

**Issue by LouisAldorio** [781flyingdutchman/background_downloader#84]
To reproduce this, you can build your app with

`flutter build apk --split-per-abi`

After that install it on your device and close the wifi and start using the cellular mobile data

The progress bar in the notification keep going, until it almost finish then error, instead of completed

**Comment by 781flyingdutchman** [comment]
Hi, sorry you're having trouble. Changing network conditions are difficult for any connection, and it is quite possible that a changeover to a different network context causes an error at the OS level that causes the download task to fail. That's why it's advisable to set retries > 0 and allow the downloader to restart the download in this new context.  If you are comfortable sharing the logs then I'm happy to take a look at it, but I expect there isn't much I can do about it as it's the underlying OS (Android, in its many flavors on different devices) that manages a network context change - the downloader simply reacts to the error it is presented with.  For comparison, iOS has a much more robust system at the OS level for managing downloads, and - for example - pauses and resumes a download as the network connection changes. Android just throws up its hands...

**Comment by LouisAldorio** [comment]
I think you missunderstood me, what I mean is not while downloading , change the network context, but from the beginning before download use mobile celullar and after the mobile cellular is on then start the download. it fails.

Edit : from my observation, for example audio file with duration of 1 minutes, the download is success with celullar, but if the duration > 1 minutes, always fails, but with wifi, everything is good

**Comment by 781flyingdutchman** [comment]
Ok - not something I can replicate though: I can download a 50MB file over cellular without any issues, and I don't think there is anything fundamentally different about cellular vs WiFi (the plugin is not aware of the type of network connection), so I don't think this is a plugin issue. Perhaps if you can share logs I am happy to take a look and see if there is anything in there that points to the problem.

**Comment by LouisAldorio** [comment]
![image](https://github.com/781flyingdutchman/background_downloader/assets/64881244/70e9c3bb-9d92-469e-bde2-350e862b0c85)

That is the log, connection reset

**Comment by 781flyingdutchman** [comment]
Yes, that's a network connection issue that has nothing to do with the background_downloader package. The OS throws a socketException and the plugin appropriately responds by failing the download - there is nothing else the plugin can do. I don't know what causes your connection reset, possibly just poor cellular connection or congestion.

**Comment by 781flyingdutchman** [comment]
In version 7.9.1 you can resume a failed task, starting it where the error occurred (if possible). This also applies to retries, so setting retries > 0 should let the downloader attempt to continue after that failure.
