### ISSUE TITLE
Migrating `flutter_downloader` database

### ISSUE THREAD

**Issue by markst** [781flyingdutchman/background_downloader#86]
I wonder if any effort has been made to migrate existing `flutter_downloader` database to `background_downloader`?

**Comment by markst** [comment]
https://github.com/nullxception/boorusphere/issues/127

**Comment by 781flyingdutchman** [comment]
That's an interesting idea @markst !  The example app contains a crude SQLite [implementation](https://github.com/781flyingdutchman/background_downloader/blob/main/example/lib/sqlite_storage.dart) of the [PersistentStorage](https://pub.dev/documentation/background_downloader/latest/background_downloader/PersistentStorage-class.html) interface that you need to implement to use a different database. It's `initialize` method is called once at start, and is meant to manage migrations, so it's relatively easy to create a migration from one SQL database (from FlutterDownloader) to another.

The crude implementation I included with the example app simply stores the JSON representation of the various objects in a table with two columns: `taskId` and `objectJsonMap`, but it's trivial to do this as a proper SQLite table with fields for each of the object fields.

Let me know if anyone is interested in creating a version of this that also migrates the FlutterDownloader SQLite table when - in the `initialize` method - it detects that such a table exists.

**Comment by 781flyingdutchman** [comment]
I added `SQLitePersistentStorage` that changes the backing database to SQLite (instead of the LocalStore package), and also automates migration from LocalStore AND from Flutter Downloader (migrating tasks in its sqlite database to our database).  @markst (or anyone else for that matter), can you perhaps take a look and see if this works as intended?  It's on the `sql` branch and you'll have to start your code like this:
```agsl
final sqlStorage = SqlitePersistentStorage(migrationOptions: ['flutter_downloader']);
FileDownloader(persistentStorage: sqlStorage);
// start using the FileDownloader
```
If you have an existing Flutter Downloader database, you should find our complete, failed and canceled tasks are now available as a `TaskRecord` via the `database` field of the downloader.

**Comment by markst** [comment]
This is awesome @781flyingdutchman! sure it will be a great help for others migrating given `flutter_downloader` is discontinued. 

Just checked out `sql` branch and unfortunately the migration doesn't seem to have worked. I have about four downloads in my previous `flutter_downloader` sql database. 

But upon launching with sqlStorage persistent storage; my previous downloading nor my new downloads are retrieving upon: 
```dart
final tasks = await FileDownloader().database.allRecords();
```

**Comment by 781flyingdutchman** [comment]
Okay, and you are constructing the SqlitePersistentStorage object with the parameter migrationOptions: ['flutter_downloader'] and there isn't already a new Sqlite database (i.e. the log says its creating a new one)? Do you know the file path of the Flutter Downloader database? Is this on Android or iOS?

I've been having a hard time getting FDL to work for testing so it's been tough to test this well - really appreciate your help!

**Comment by markst** [comment]
Seems `FlutterDownloaderPersistentStorage.retrieveAllTaskRecords()` is throwing exception:
`FormatException (FormatException: Unexpected character (at character 1)`
Here is my existing db: https://d.pr/f/zT4HBz.sql

**Comment by markst** [comment]
I think `headers` is malformed and so `Map.castFrom(jsonDecode(fdlTask['headers'] as String))` is failing:

<img width="742" alt="image" src="https://github.com/781flyingdutchman/background_downloader/assets/274318/d9f95543-f2a1-477d-a3e3-9c9be6503e10">

**Comment by markst** [comment]
906a039b9c6c19994d2ff5f7afc90ac2bf818f74 seems to resolve it for me, a migration of `flutter_downloader` is working! I haven't tested migration of `LocalStore`.

**Comment by 781flyingdutchman** [comment]
Awesome! Can you create a pull request (or ai can just copy/paste from your commit). The LocalStore migration is easier as I "control" both.

**Comment by 781flyingdutchman** [comment]
OK, as always it's harder than it looks, because there is no indication that the FDL actually url-encodes the headers in the database (based on the current version of the package).  I therefore implemented it as I had, but with a fallback if there's a FormatException, then url-decode.

Published now as version 7.6.0 - I am still uneasy about the iOS migration but we'll see how it goes! Thanks for your help!

**Comment by markst** [comment]
Hey @781flyingdutchman. Been testing this on Android and I'm sorry to say it isn't quite working as expected. 

Seems migration does and my Task's are migrated. However seems the `Task.filePath()` no longer resolves to the correct location.

This is the actual path for my downloads should be:
```
/data/user/0/au.org.pbsfm.flutter/cache/downloads/Deeep Space - 3 July 2023.mp3
```
but after migration the `filePath()` resolves to:
```
"/data/user/0/au.org.pbsfm.flutter/app_flutter/Deeep Space - 3 July 2023.mp3"
```

I'll try and do some more digging. but seems maybe `getDirectories` isn't resolving correctly. 

Here's a snippet of my previous `flutter_downloader` implementation:
```dart
final externalDir = await (Platform.isIOS ? getApplicationDocumentsDirectory() : getTemporaryDirectory());
final savedDir = await Directory("${externalDir.path}/downloads").create();

final taskId = await FlutterDownloader.enqueue(
  url: uri.toString(),
  savedDir: savedDir.path,
```

might add that it be good to review pull request before tagging releases 😬

**Comment by 781flyingdutchman** [comment]
Hi, thanks for testing and apologies for not covering this better with tests. I only test the docs for, and didn't come across this. Looking at the repo, I think the issue is in line 365 where docsdir is hard coded and should be the directory pointed to by `directory`. I'll do some testing when I get home and see if I can release a bug fix.

**Comment by markst** [comment]
ah I can take a look do some testing & open a PR!

did you only add `SQLitePersistentStorage` of my benefits?
I thought I remember you saying at one stage you didn't want to go down the SQL route!

**Comment by 781flyingdutchman** [comment]
Turned out the directory parsing was way off, and much more complicated than I thought. I've now tested it thoroughly on Android and iOS (though I am still unable to test the actual Flutter Downloader on iOS, so there's a chance I'm not picking up the right SQLIte database to use - would be great if you could test this on an iPhone with residual Flutter Downloader database).

The new version is on the `sql` branch until tested :)

As for SQLite: I chose the original LocalStore package because it is very simple, pure Dart, works on all platforms that background_downloader supports, and does not add a significant dependency (especially after integrating the package as I needed some bug fixes that the author was unable to make - this is a general problem with flutter packages, IMHO).  However, the `PersistentStorage` interface approach decouples the underlying database, and it seemed logical to add an SQlite implementation, as it's obviously faster, more reliable and powerful. The nice thing is that if you choose not to use it (i.e. the default), the Flutter compiler will tree-shake it out, so there is no dependency when you don't need it. It also made it easier then to implement FDL migration.

So yes, I caved again :)

**Comment by markst** [comment]
amazing. just tested on Android and seemed to work well!
afraid iOS didn't seem to migrate, will have to do some digging as to why.

**Comment by 781flyingdutchman** [comment]
Thanks for testing!  For iOS, as I said I can't get the FDL to work so I can't really test.  The places to look for issues are:
1. Location of the FDL database (happens in `getDatabasePath()` in the `FlutterDownloaderPersistentStorageIOS` class
2. Field/column names of that database. I have assumed they are the same as on Android, based on the ObjC code in the FDL main repo
3. Contents of the fields (i.e. how they are encoded).  As we've seen with headers, there may be differences there that trip up the code in `retrieveAllTaskRecords()` in the `FlutterDownloaderPersistentStorage` class
4. Extracting the proper `saved_dir` and translating it into 'our' `BaseDirectory`/`directory` structure.  This is very likely an issue, as - as you know - iOS changes the path to the app's docsDir, so I've added further logic for that in the latest push on `sql`, where I replace the App Identifier in `savedDir` if it is different from the current app identifier (i.e. was stored on a previous run of the app). The unit tests suggest it works, but please try this new version (just pushed).
Note that if savedDir cannot be resolved to a `BaseDirectory`/`directory` , the record is skipped not migrated. This will be true, for instance, if on Android it is stored in an external directory. That really doesn't fit the storage model we've adopted.

Please let me know what you find.

**Comment by 781flyingdutchman** [comment]
I've included this in the latest update as a bug fix, and added a warning that the migration is still experimental. Felt it would be helpful to at least have the Android migration work for everyone, and hopefully the iOS one.  Leaving this open as I'd love  to hear if it works on iOS.

**Comment by markst** [comment]
Just had a quick test on iOS and it's failing to parse `saved_dir`.

I think the issue stems from the half baked handling of directories on iOS `flutter_downloader` for the directory.

I think the expectation on iOS is to use relative directory for the `DownloadTask.directory`.
Since the `absoluteSavedDirPath` is generated when fetching tasks records:
https://github.com/fluttercommunity/flutter_downloader/blob/master/ios/Classes/FlutterDownloaderPlugin.m#L571C53-L571C53

Perhaps the `getDirectories` should assume `BaseDirectory.applicationDocuments` if no match is found.
As the documentation mentions:
https://github.com/fluttercommunity/flutter_downloader/blob/master/README.md?plain=1#L172

**Comment by 781flyingdutchman** [comment]
Ok, do you have a few examples of paths in the savedDir column of the database on iOS? Just trying to understand what they're like, and what they're relative to if they're not absolute. Thanks!

**Comment by markst** [comment]
here's a bit of background: https://github.com/fluttercommunity/flutter_downloader/issues/69
one such sql database with two entries: https://d.pr/f/89FnLK
`enqueueMethodCall` -> will translate passed `savedDir` using `shortenSavedDirPath` which results in the absolute path persisted to sql `saved_dir` table.

**Comment by 781flyingdutchman** [comment]
Thanks, that's helpful. I included it with a small change, where if - for some reason - the subdir starts with a '/' we do return null (otherwise creating a task with a leading platform separator in `directory` creates an error).  Thanks again for your help - hopefully this finally puts this migration to rest.

**Comment by markst** [comment]
Legend, thanks! Will give it some more testing. How do I buy you a beer or similar?

**Comment by 781flyingdutchman** [comment]
All good, hope it works - let me know!
