### ISSUE TITLE
how to create parallel progress callback for everytask

### ISSUE THREAD

**Issue by rrickyzz** [781flyingdutchman/background_downloader#87]

**Comment by rrickyzz** [comment]
given that i have downloaded multiple files(not batch), how can i listen to individual progress call back so i can show all the real time progress in my download page. thank you

**Comment by 781flyingdutchman** [comment]
Hi, in short: use `enqueue` instead of `download` and your listener will receive every status and progress update. Within the listener, differentiate your behavior based on the task's `taskId` or `group`.

For example, define your listener in `initState`:
```
    // Listen to updates and process
    FileDownloader().updates.listen((update) {
      switch (update) {
        case TaskStatusUpdate _:
          // do something with the statusUpdate, which has a `task` and `status` field
         print('TaskId ${update.task.taskId} status = ${update.status}');

        case TaskProgressUpdate _:
          // do something with the progressUpdate, which has a `task` and `progress` field
         print('TaskId ${update.task.taskId} progress = ${update.progress * 100} %');
      }
    });
```

Every task you `enqueue` will get updates through the listener. Make sure to define the task's `update` field to include progress updates, as by default a task only generates status updates.

See [documentation](https://pub.dev/packages/background_downloader#using-an-event-listener).

**Comment by 781flyingdutchman** [comment]
Hi, in short: use `enqueue` instead of `download` and your listener will receive every status and progress update. Within the listener, differentiate your behavior based on the task's `taskId` or `group`.

For example, define your listener in `initState`:
```
    // Listen to updates and process
    FileDownloader().updates.listen((update) {
      switch (update) {
        case TaskStatusUpdate _:
          // do something with the statusUpdate, which has a `task` and `status` field
         print('TaskId ${update.task.taskId} status = ${update.status}');

        case TaskProgressUpdate _:
          // do something with the progressUpdate, which has a `task` and `progress` field
         print('TaskId ${update.task.taskId} progress = ${update.progress * 100} %');
      }
    });
```

Every task you `enqueue` will get updates through the listener. Make sure to define the task's `update` field to include progress updates, as by default a task only generates status updates.

See [documentation](https://pub.dev/packages/background_downloader#using-an-event-listener).
