### ISSUE TITLE
How can i upload multiple files in one request?

### ISSUE THREAD

**Issue by beroso** [781flyingdutchman/background_downloader#88]

**Comment by 781flyingdutchman** [comment]
Use `uploadBatch`. Please read the [documentation](https://pub.dev/packages/background_downloader#a-batch-of-files).

**Comment by beroso** [comment]
Sorry for not specifying the problem properly. 
I consume an api that requires three files in a single POST request.
I would like to know if it is possible to upload multiple files to a single endpoint/request. I read the docs and not found a way to do it.

**Comment by 781flyingdutchman** [comment]
Ah yes, that is indeed entirely different - sorry for not getting that. Currently, that is not supported, but the multipart file upload 'protocol' does support it, so let me look into whether/how this can be done.  This will probably take a bit, so re-opening this with the 'enhancement' tag - stay tuned!

**Comment by 781flyingdutchman** [comment]
@beroso can you see if the implementation of multiple uploads in one request works?

You need to define a `MultiUploadTask` instead of an `UploadTask` and pass a `files` parameter that is the list of files to upload. Each element is either a `String`, eg "file.txt", or a `record` with the file field name and the filename, e.g. `("f1", "file.txt")` or a record with file field name, filename and mimetype, e.g. `("f1", "file.txt", "text/plain")`. The file should be in the directory indicated by `baseDirectory` and `directory` (just like with others tasks), although if you give a full absolute filepath (e.g. "/data/com.app/dir/file.txt" instead of "file.txt" in he examples above) that will ignore those two and just take the absolute filepath.

Other than that, it works the same: call `FileDownloader().upload(theMultiUploadTask)` or use `enqueue`.

Please test it on as many platforms as you can, and let me know if it works.

**Comment by beroso** [comment]
Awesome! I will test it ASAP!

**Comment by beroso** [comment]
Tested on Android, it's working fine! I will continue to test other platforms soon.

**Comment by 781flyingdutchman** [comment]
I've tested it on iOS and Desktop too, so I think it'll work fine if it works on Android Added to version 7.7.0 - let me know if you run into any issues
