### ISSUE TITLE
Download restart when leaving the app, not kill the app , the app is in the task manager

### ISSUE THREAD

**Issue by LouisAldorio** [781flyingdutchman/background_downloader#89]
The progress bar in notification freeze when I leave the app and open other app (note : the app is not killed or close entirely, just put in the background / paused) , and when come back to the app the frozen download in notification start again from the beginning.

**Comment by 781flyingdutchman** [comment]
Hi, most likely the OS kills the background task when you move the app to the background, and therefore the download has to restart when the app moves to the foreground. There are many reasons the OS may choose to kill the app, e.g. network connection changes, resource constraints etc. If you send logs I'm happy to take a look and let you know what's happening.

I understand this is not ideal behavior, but it's due to the limitations of your specific device and environment. The downloader leverages the underlying OS, and the OS manages access to device resources.

Also, as a general suggestion, when you file an issue please add details: what version of the package are you using, on what OS and device does this issue occur, what *exactly* is happening and what did you *expect* to happen, share logs, share properly formatted code snippets where you interact with the package. Without this we need to go back and forth several times, and package development is typically just volunteer work. Thanks!

**Comment by 781flyingdutchman** [comment]
See also your own issue #84 (same situation, in that case triggered by a poor network connection) and issue #77 that actually did uncover a bug, but explains more about how Android manages (and kills) background tasks

**Comment by LouisAldorio** [comment]
After few observation, I do the same thing in the emulator , the task continue , but on real device, the task is canceled. Here is the log, maybe you can help to find out what is wrong ?

![image](https://github.com/781flyingdutchman/background_downloader/assets/64881244/e84852f0-5f09-4f0e-ba37-e9acafd88d46)

Here is my implementation
main.dart
![image](https://github.com/781flyingdutchman/background_downloader/assets/64881244/58017bda-3dd6-4e94-8360-5e6186e01adb)

My Home Activity , I register the callbacks needed, and un register everything before the home activity is rendered , also unregister in Close
![image](https://github.com/781flyingdutchman/background_downloader/assets/64881244/c060a047-c6e0-4b05-a2c0-fa6f4c7d0665)
![image](https://github.com/781flyingdutchman/background_downloader/assets/64881244/5e8ee962-a051-4a1f-9fee-72a60861c1bc)


Here is certain Activity where I enqueue the task
![image](https://github.com/781flyingdutchman/background_downloader/assets/64881244/9144e080-8a75-48e3-91e9-e90a354c5355)

This is strange, why does it work well on emulator but not on real device?

**Comment by 781flyingdutchman** [comment]
Hi, thanks for sharing! Good news: you're doing everything correctly. Bad news: the OS cancels the background task, and I don't really know why. Is there anything in the logs before that cancellation message that gives a hint, e.g. is there perhaps a low memory situation, or another set of tasks that is running? The only explanation I can give is that there is some constraint that causes the OS to decide it doesn't want to dedicate resources to a background task when the associated app is not in the foreground. As you can see it does work in the emulator, and it has worked for me for the (real) devices I have tested it on (and it has for many other users of the package) so I can only surmise that there is something on your phone that makes it decide to shut down the background tasks.

Some Googling suggests this is not unique, eg see [here](https://stackoverflow.com/questions/64859742/why-wont-workmanager-run-my-job-if-my-app-is-closed) (caused by battery optimization settings), and [this article](https://stackoverflow.com/questions/50682061/android-is-workmanager-running-when-app-is-closed) suggest some device OEMs implement the OS such that it does indeed kill background tasks. I don't know what device you are using, but would suggest trying it on a few other devices, including eg a Pixel (with stock Android) to see what happens.

Unfortunately, I cannot control the OS cancelling a WorkManager task - therefore I'm afraid there is nothing I can do about this to help you address the issue.

I am going to leave this issue open and hope someone else has insights or ideas on how to address this.

**Comment by LouisAldorio** [comment]
The Plugin only provides background processing, will it implement foreground service so that it is less vulnerable to being killed by the os regarding resource optimization?, or do you have any suggestion to make the background task immune to os Kill ?

**Comment by 781flyingdutchman** [comment]
I understand your frustration! I've looked into setting this up as a foreground service, but that has all kinds of downsides so I decided not to go down that route. I don't know what will make the task immune to getting killed, but as I understand it, turning off battery saver and optimizer, maximizing amount of free memory, disabling 'doze' if possible should all increase your chances that the OS wil let the task live. And on some devices, especially less powerful ones, it may always get killed, as the OEM wants to maximize foreground performance.

**Comment by 781flyingdutchman** [comment]
We may be addressing with through issue #104 so please follow along there and try out development commits that show up there.

**Comment by 781flyingdutchman** [comment]
I've added the notion of configuration, and the first configuration is for setting the Android 'runInForeground' mode, which hopefully gets around your issue (the aggressive cancellation of background tasks).

I could really use your help testing this, both for uploads and downloads

Please update your pubspec.yaml to:
```
background_downloader:
    git:
      url: https://github.com/781flyingdutchman/background_downloader.git
      ref: config
```
Configuration is 'global', so once you configure something it stays in place until you change the config.

To configure the downloader to run everything in foreground mode, call:
```
    final configResult = await FileDownloader()
        .configure(androidConfig: ('runInForeground', true));
```
Note the argument to `.configure` is a record (and can be a list of records), hence the brackets.  The `configResult` is a list containing records where the first item is the configuration string used, followed by an empty string if all went well.

For every task running after this, you should now see several references to 'foreground' in the log, except the last notification update (for 'complete' or 'failed') should NOT be in foreground (because otherwise it disappears).

You can also configure it such that it runs in foreground only for uploads/downloads above a certain size (expressed in MegaBytes) as follows:

```
    final configResult = await FileDownloader()
        .configure(androidConfig: ('runInForegroundIfFileLargerThan', 10));
```

Whichever config you use last will apply.

Please test this as thoroughly as you can, and let me know what you find.

**Comment by LouisAldorio** [comment]
Thanks sir but currently I am in hospital , will test it soon after recover

**Comment by 781flyingdutchman** [comment]
Sorry to hear that! Get well soon!

**Comment by LouisAldorio** [comment]
Hi sir, I have tried it, the task is immute to kill, but it does not broadcast event anymore to the registered callback somehow, show after the task is finished everything inside the registered callback to handle the task finished, cannot be executed, but from the immunity to not be killed by OS, it works well

**Comment by 781flyingdutchman** [comment]
HI, glad you're back, and thanks for testing!  If you close the app totally (i.e. swipe it away in the task manager, often referred to as _killing_ the app, as opposed to _closing_ it)) then the behavior you describe is as expected. If you _close_ the app (e.g. by tapping the 'home' button or opening another app - without messing with the task manager) then the task and updates should continue. Can you confirm that's the behavior you're seeing?

I can't really do anything about the user killing the app - that is their intent, and the OS kills associated code without any warning.

**Comment by 781flyingdutchman** [comment]
Included 'runInForeground' configuration for Android in V7.9.0

**Comment by LouisAldorio** [comment]
Okay thankyou sir
